### ISSUE TITLE
✨ [Feat] 친구 요청 거절 API 구현 및 테스트

### ISSUE THREAD

**Issue by Eunjin3395** [Gamegoo-repo/Gamegoo-Server-v2#29]
## 📝 기능 개요

친구 요청 거절 API 구현 및 테스트

## ✅ Todo
- [x] 친구 요청 거절 API 구현
- [x] 친구 요청 거절 API 서비스 테스트
- [x] 친구 요청 거절 API 컨트롤러 테스트
