### ISSUE TITLE
✨ [Feat] 이메일 인증 API 구현 및 테스트

### ISSUE THREAD

**Issue by rimi3226** [Gamegoo-repo/Gamegoo-Server-v2#37]
## 📝 기능 개요
이메일 인증 구현 API 구현 및 테스트

## ✅ Todo
- [ ] 이메일 전송 메서드 구현
- [ ] 회원가입용 이메일 API 구현
- [ ] 이메일 테스트 코드 작성
