### ISSUE TITLE
✨ [Feat] 알림 생성 이벤트 및 리스너 구현

### ISSUE THREAD

**Issue by Eunjin3395** [Gamegoo-repo/Gamegoo-Server-v2#41]
## 📝 기능 개요

알림 생성 메소드 구현

## ✅ Todo
- [x] 알림 생성 이벤트 구현
- [x] 알림 생성 이벤트 리스너 구현
- [x] 알림 생성 메소드 구현
- [x] 알림 생성 메소드 테스트
- [x] 친구 관련 서비스 코드에 알림 로직 추가
- [x] 친구 관련 테스트 코드에 알림 검증 추가
