### ISSUE TITLE
✨ [Feat] 소환사명으로 친구 검색 API 구현 및 테스트

### ISSUE THREAD

**Issue by Eunjin3395** [Gamegoo-repo/Gamegoo-Server-v2#43]
## ✅ Todo
- [ ] 소환사명으로 친구 검색 API 구현
- [ ] 소환사명으로 친구 검색 API 서비스 테스트
- [ ] 소환사명으로 친구 검색 API 컨트롤러 테스트
