### ISSUE TITLE
✨ [Feat] 알림 읽음 처리 API 구현 및 테스트

### ISSUE THREAD

**Issue by Eunjin3395** [Gamegoo-repo/Gamegoo-Server-v2#52]
## 📝 기능 개요

알림 읽음 처리 API 구현 및 테스트

## ✅ Todo
- [x] 알림 읽음 처리 API 구현
- [x] 알림 읽음 처리 API 통합 테스트
- [x] 알림 읽음 처리 API 컨트롤러 테스트
