### ISSUE TITLE
✨ [Feat] 안읽은 알림 개수 조회 API 구현 및 테스트

### ISSUE THREAD

**Issue by Eunjin3395** [Gamegoo-repo/Gamegoo-Server-v2#55]
## 📝 기능 개요

안읽은 알림 개수 조회 API 구현 및 테스트

## ✅ Todo
- [x] 안읽은 알림 개수 조회 API 구현
- [x] 안읽은 알림 개수 조회 API 통합 테스트
- [x] 안읽은 알림 개수 조회 API 컨트롤러 테스트
