### ISSUE TITLE
✨ [Feat] 알림 전체/팝업 목록 조회 API 구현 및 테스트

### ISSUE THREAD

**Issue by Eunjin3395** [Gamegoo-repo/Gamegoo-Server-v2#57]
## 📝 기능 개요

알림 전체/팝업 목록 조회 API 구현 및 테스트

## ✅ Todo
- [x] 알림 전체 목록 조회 API 구현
- [x] 알림 전체 목록 조회 API repository 테스트
- [x] 알림 전체 목록 조회 API 통합 테스트
- [x] 알림 전체 목록 조회 API 컨트롤러 테스트
- [x] 알림 팝업 목록 조회 API 구현
- [x] 알림 팝업 목록 조회 API repository 테스트
- [x] 알림 팝업 목록 조회 API 통합 테스트
- [x] 알림 팝업 목록 조회 API 컨트롤러 테스트
