### ISSUE TITLE
✨ [Feat] 특정 회원과 채팅방 시작 API 구현 및 테스트

### ISSUE THREAD

**Issue by Eunjin3395** [Gamegoo-repo/Gamegoo-Server-v2#61]
## 📝 기능 개요

특정 회원과 채팅방 시작 API 구현 및 테스트

## ✅ Todo
- [x] 특정 회원과 채팅방 시작 API 구현
- [x] RepositoryTestSupport 구현 및 리팩토링
- [x] chatRepository 테스트
- [x] chatroomRepository 테스트 
- [x] ChatResponseFactory 단위 테스트
- [x] 특정 회원과 채팅방 시작 API 통합 테스트
- [x] 특정 회원과 채팅방 시작 API 컨트롤러 테스트
