### ISSUE TITLE
✨ [Feat] 특정 채팅방 입장 API 구현 및 테스트

### ISSUE THREAD

**Issue by Eunjin3395** [Gamegoo-repo/Gamegoo-Server-v2#70]
## 📝 기능 개요

특정 채팅방 입장 API 구현 및 테스트

## ✅ Todo
- [x] 특정 채팅방 입장 API 구현 
- [x] 특정 채팅방 입장 API 서비스 테스트
- [x] 특정 채팅방 입장 API 컨트롤러 테스트
