### ISSUE TITLE
✨ [Feat] 채팅 메시지 등록 API 구현 및 테스트

### ISSUE THREAD

**Issue by Eunjin3395** [Gamegoo-repo/Gamegoo-Server-v2#79]
## 📝 기능 개요

채팅 메시지 등록 API 구현 및 테스트

## ✅ Todo
- [x] 채팅 메시지 등록 API 구현
- [x] 채팅 메시지 등록 서비스 테스트
- [x] 채팅 메시지 등록 API 통합 테스트
- [x] 채팅 메시지 등록 API 컨트롤러 테스트
