### ISSUE TITLE
✨ [Feat] 특정 채팅방의 메시지 내역 조회 API 구현 및 테스트

### ISSUE THREAD

**Issue by Eunjin3395** [Gamegoo-repo/Gamegoo-Server-v2#84]
## 📝 기능 개요

특정 채팅방의 메시지 내역 조회 API 구현 및 테스트

## ✅ Todo
- [x] 특정 채팅방의 메시지 내역 조회 API 구현
- [x] 특정 채팅방의 메시지 내역 조회 repository 테스트
- [x] 특정 채팅방의 메시지 내역 조회 API 통합 테스트
- [x] 특정 채팅방의 메시지 내역 조회 API 컨트롤러 테스트
