### ISSUE TITLE
✨ [Feat] 채팅방 읽음 처리 API 구현 및 테스트

### ISSUE THREAD

**Issue by Eunjin3395** [Gamegoo-repo/Gamegoo-Server-v2#97]
## 📝 기능 개요

채팅방 읽음 처리 API 구현 및 테스트

## ✅ Todo
- [x] 채팅방 읽음 처리 API 구현
- [x] 채팅방 읽음 처리 API 통합 테스트
- [x] 채팅방 읽음 처리 API 컨트롤러 테스트
